import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Providers } from "./component/provider";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Providers>
            <Navbar />
            <main className="px-6 max-w-full mx-auto">{children}</main></Providers>
            <Footer/>
       
      </body>
    </html>
  );
}
